### ISSUE TITLE
Noisy marching cube mesh

### ISSUE THREAD

**Issue by manhha1402** [chrdiller/KinectFusionLib#4]
Hi,
I test the marching cube algorithm. It provides a noisy marching cube mesh as a picture.  Do you have the result like it ? Thanks !
![noisy_mesh](https://user-images.githubusercontent.com/20105284/40874313-fe5eea4a-666d-11e8-8e3e-29fba5ed0546.png)

**Comment by chrdiller** [comment]
Hi, 

this is more or less the expected behaviour as I only implemented a very basic version of Marching Cubes to run as fast as possible on the GPU. To get a better result, one should use some interpolation. I might update this implementation at some point; if you feel like working on it, feel free to open a pull request, I would be very happy to integrate it :)

**Comment by manhha1402** [comment]
thanks !

**Comment by mihaibujanca** [comment]
@manhha1402 @chrdiller there's a marching cubes example in the cuda samples - it doesn't look like it should be that hard to adapt for this and I'm expecting it would be a better implementation since it's the official version.

Runs at 1300 fps on my GPU with a 32 x 32 x 32 volume.

I'm currently not saving meshes so I probably won't be working on this anytime soon but if either of you gets around to do it, would be really cool!

**Comment by manhha1402** [comment]
I am working for the way to map UV coordinates on a mesh model. I have tried Poisson reconstruction and Fast Greedy Triangulation that generate mesh model from point cloud, implemented in PCL library and map textures to the model. These algorithms only work for convex objects. Marching Cubes works well on both convex and concave objects but it provides a quite noisy model.

**Comment by mihaibujanca** [comment]
On this topic, gave it a try with the current marrching cubes (and raycasting for that matter) when surfaces aren't closed. Seems like there are some issues with depth discontinuities, please see attached.

![screenshot from 2018-06-25 22-27-57](https://user-images.githubusercontent.com/3803777/41876839-1c870c4e-78c7-11e8-8448-a7ea2c812b87.png)
![screenshot from 2018-06-25 22-28-05](https://user-images.githubusercontent.com/3803777/41876840-1ca147e4-78c7-11e8-8ecd-7c3555e1c800.png)

I'll probably try integrating the CUDA sample marching cubes towards the end of the week
