### ISSUE TITLE
Questions about pose_estimation.cu

### ISSUE THREAD

**Issue by mihaibujanca** [chrdiller/KinectFusionLib#5]
Hi, apologies if the answer to these should be obvious - I'm still learning cuda.

I was wondering what the reduce / reduction kernel functions are for and why are 27 blocks used specifically?
In  `pose_estimation.cu:200`
```
    reduction_kernel<<<27, 512>>>(global_buffer, grid.x * grid.y, sum_buffer);
```

**Comment by chrdiller** [comment]
This is due to the KinectFusion optimization formulation.
We estimate Ax = b for all pixels where A is a 6x6 matrix and b is a 6 element vector. 
global_buffer collects A and b for each pixel and in the end we want to sum that up into sum_buffer; the reduce kernel is just a general and efficient way of doing that on the GPU. 

27 is the number of elements we sum up over all pixels; this is also due to the nature of A and b. A is a symmetric matrix so we can focus on calculating only the upper triangular matrix and get 21 values for A and 6 for b.

Then we convert it into the actual matrix in lines 205-214 after downloading.

**Comment by mihaibujanca** [comment]
Thanks very much, makes sense!
